# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eca3869e82367b7dd162c5d51aea9c130c35615120cfd026f76cae254f0b22607563a507b2a9172c13d639baee05d4aaac107ef430b6529686c33d6531f9c07b

test:
  secret_key_base: e25d192d55b047b59f0cafc3410c237a3098e7240b482138c32a5fbd03dba44c69849f457a2911bd5ef86142a66ad551cac9b9d8a569e77e33ba55064bc899bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
